name: Auto Deploy

on:
  push:
    branches:
      - dev  # หรือเปลี่ยนเป็น branch ที่คุณใช้

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull latest Docker image
      run: |
        cd /home/nc-user/Project/Dev
        # ใช้ docker-compose ดึง Docker image ล่าสุดจาก registry
        docker-compose -f docker-compose.dev.yml pull

    - name: Restart the container with the new image
      run: |
        cd /home/nc-user/Project/Dev  # ไปยัง directory ที่มี docker-compose.dev.yml
        docker-compose -f docker-compose.dev.yml down  # ปิด container ที่กำลังรันอยู่
        docker-compose -f docker-compose.dev.yml up -d  # เริ่ม container ใหม่ด้วย image ล่าสุด
